/*
Author: Eli Elad Elrom
Website: https://EliElrom.com
License: MIT License
Component: src/types.ts
*/

export namespace Types {
  export type TemplateData = {
    Template_id: string
    Version: string
    Template: string
  }
  export type CategoriesData = {
    value: string
  }
  export type FieldsData = {
    value: string
  }
  export type UpdateTemplateData = {
    name: string,
    fields: string,
    category: string
  }
  export type VariablesData = {
    // eslint-disable-next-line max-len
    record_id: string
    template_id: string
    template_version: string
    time_window_id: string
    severity: string
    appname: string
    host: string
    procid: string
    msgid: string
    facility: string
    version: string
    timestamp: string
    otherheaders: string
    timestamp_1: string
    SearchFields: string
    num_1: string
    num_2: string
    num_3: string
    pack_auto_log_1: string
    wpa_supplicant_1: string
    len_1: string
    num_4: string
    num_5: string
    num_6: string
    num_7: string
    num_8: string
    num_9: string
    num_10: string
    alphanumerical_1: string
    alphanumerical_2: string
    num_11: string
    num_12: string
    num_13: string
    alphanumerical_3: string
    alphanumerical_4: string
    num_14: string
    alphanumerical_5: string
    alphanumerical_6: string
    num_15: string
    alphanumerical_7: string
    alphanumerical_8: string
    num_16: string
    num_17: string
    alphanumerical_9: string
    alphanumerical_10: string
    num_18: string
    num_19: string
    num_20: string
    num_21: string
    num_22: string
    num_23: string
    num_24: string
    timestamp_2: string
    activity_manager_1: string
    alphanumeric_chain_two_1: string
    base_activity_1: string
    native_player_1: string
    netd_connector_1: string
    _$_1: string
    _$_2: string
    _$_3: string
    _$_4: string
    sdk_1: string
    alphanumeric_chain_three_1: string
    process_info_collector_1: string
    alphanumerical_11: string
    alphanumerical_12: string
    alphanumerical_13: string
    alphanumerical_14: string
    alphanumerical_15: string
    alphanumerical_16: string
    alphanumerical_17: string
    alphanumerical_18: string
    alphanumerical_19: string
    alphanumerical_20: string
    timestamp_3: string
    data_migrate_utils_1: string
    activity_manager_broadcast_1: string
    p_1: string
    m_key_val_1: string
    euid_1: string
    hw_pfwlogger_1: string
    authentication_service_1: string
    type_1: string
    result_1: string
    ip_1: string
    qims_service_1: string
    ipvfour_1: string
    is_1: string
    wpa_1: string
    mac_1: string
    ver_1: string
    connection_service_wrapper_1: string
    telecom_1: string
    num_25: string
    num_26: string
    wifi_monitor_1: string
    cnt_1: string
    dispatch_event_1: string
    depth_1: string
    cn_1: string
    hash_1: string
    hw_arp_verifier_1: string
    ipaa_1: string
    hex_1: string
    fpc_fingerprint_hal_1: string
    seq_1: string
    apm_audio_policy_manager_1: string
    activity_manager_service_1: string
    thread_1: string
    pid_1: string
    procname_1: string
    huawei_wifi_watchdog_state_machine_1: string
    m_high_data_flow_rate_1: string
    hw_vdrive_1: string
    caller_app_1: string
    flags_1: string
    sensor_state_1: string
    powergenie_jni_1: string
    mode_1: string
    wifi_state_machine_1: string
    ticks_bad_1: string
    ticks_not_high_1: string
    wifi_scan_genie_controller_1: string
    id_1: string
    automatic_brightness_controller_1: string
    audio_hw_primary_1: string
    point_width_1: string
    skiplowlevel_1: string
    hw_broadcast_queue_1: string
    qiyippsplay_1: string
    num_27: string
    num_28: string
    hcdn_downloadengine_1: string
    status_1: string
    get_game_tips_data_1: string
    state_1: string
    tips_controller_1: string
    audio_flinger_1: string
    stream_1: string
    value_1: string
    magic_link_1: string
    when_1: string
    what_1: string
    target_1: string
    native_player_2: string
    info_1: string
    m_movie_init_params_1: string
    m_movie_init_params_string_1: string
    count_1: string
    refresh_state_1: string
    icon_1: string
    res_id_1: string
    label_tint_1: string
    text_changed_delay_1: string
    dual_label_content_description_1: string
    minimal_content_description_1: string
    minimal_accessibility_class_name_1: string
    expanded_accessibility_class_name_1: string
    auto_mirror_drawable_1: string
    disabled_by_policy_1: string
    enforced_admin_1: string
    hw_wifi_stat_store_1: string
    num_29: string
    num_30: string
    status_bar_manager_service_1: string
    user_id_1: string
    pkg_1: string
    from_type_1: string
    hw_wifi_service_manager_impl_1: string
    failed_1: string
    address_1: string
    uname_1: string
    notification_group_manager_1: string
    group_1: string
    power_manager_service_1: string
    m_force_doze_1: string
    mrssi_1: string
    call_1: string
    nothing_1: string
    hw_wifi_qualified_network_selector_1: string
    activity_thread_1: string
    token_1: string
    sec_input_method_manager_service_1: string
    qctimeservices_1: string
    pgmanager_service_1: string
    uid_1: string
    proxy_1: string
    hw_system_manager_1: string
    limit_1: string
    warn_1: string
    used_1: string
    chr_qc_chr_modem_service_1: string
    call_state_1: string
    ncchr_log_database_nc_1: string
    metric_id_1: string
    video_pause_controller_1: string
    video_pause_controller_2: string
    e_space_app_1: string
    resume_video_1: string
    telephony_1: string
  }
  export type LogRadioState = { both: boolean; templates: boolean; variables: boolean }
}
